name: CloudComPy310
channels:
  - conda-forge
dependencies:
  - alabaster=1.0.0=pyhd8ed1ab_1
  - aom=3.6.1=h63175ca_0
  - babel=2.17.0=pyhd8ed1ab_0
  - blosc=1.21.5=hbd69f2e_1
  - boost=1.74.0=py310hc781a3c_5
  - boost-cpp=1.74.0=h9f4b32c_8
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.16.0=hd694305_1014
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310h29418f3_1
  - cfitsio=4.1.0=h5a969a9_0
  - cgal=5.4=py310hf5e1058_0
  - cgal-cpp=5.4.1=h3c2f9b9_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cmake=3.27.4=h1537add_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - curl=7.86.0=heaf79c2_1
  - cycler=0.12.1=pyhcf101f3_2
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.2.0=h63175ca_1
  - draco=1.5.7=h181d51b_0
  - eigen=3.4.0=h477610d_1
  - expat=2.7.3=hac47afa_0
  - ffmpeg=4.4.2=gpl_hf960ced_113
  - flann=1.9.1=h23a95e4_1011
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py310hdb0e946_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.12.1=hdaf720e_2
  - freexl=1.0.6=h67ca5e6_1
  - gdal=3.5.2=py310h198874d_1
  - geos=3.11.0=h39d44d4_0
  - geotiff=1.7.1=h714bc5f_3
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - gl2ps=1.4.2=h0597ee9_0
  - glew=2.1.0=h39d44d4_2
  - glib=2.80.2=h0df6a38_0
  - glib-tools=2.80.2=h2f9d560_0
  - gst-plugins-base=1.20.3=h001b923_2
  - gstreamer=1.20.3=h6b5321d_2
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h2a0e4a3_100
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - jasper=2.0.33=hc2e4405_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=hcfcfb64_3
  - jsoncpp=1.9.5=h2d74725_1
  - kealib=1.4.15=hdf81f3a_1
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.19.3=h1176d77_0
  - laszip=3.4.3=h6538335_1
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h6470a55_1
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.11.0=7_h6c93730_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=7_hc41557d_netlib
  - libclang=14.0.6=default_h77d9078_1
  - libclang13=14.0.6=default_h77d9078_1
  - libcurl=7.86.0=heaf79c2_1
  - libdeflate=1.14=hcfcfb64_0
  - libevent=2.1.10=h6a571f8_4
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libgdal=3.5.2=hc386656_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.80.2=h0df6a38_0
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libkml=1.3.0=hd45a9bc_1016
  - liblapack=3.11.0=7_h018ca30_netlib
  - liblapacke=3.11.0=7_h0d55cca_netlib
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.5.5=py310he958ad5_13
  - libpng=1.6.43=h19919ed_0
  - libpq=14.5=h04fd8be_3
  - libprotobuf=3.20.3=h12be248_0
  - librttopo=1.1.0=h2842628_11
  - libspatialite=5.0.1=hd9530bf_19
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.10.0=h680486a_3
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.4.0=hc4f729c_5
  - libvorbis=1.3.7=h5112557_2
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.12.7=h283a6d9_1
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.13=h2466b09_6
  - llvm-openmp=8.0.1=h1ad3211_0
  - loguru=0.7.3=pyh7428d3b_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib=3.5.3=py310h5588dad_2
  - matplotlib-base=3.5.3=py310h7329aa0_2
  - mpfr=4.2.1=h64bf75a_1
  - mpir=3.0.0=he025d50_1002
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.0.30=h9752425_0
  - mysql-client=8.0.30=hf8b63c5_0
  - mysql-common=8.0.30=hd2cd81a_0
  - mysql-devel=8.0.30=hd2cd81a_0
  - mysql-libs=8.0.30=h4d1747d_0
  - mysql-server=8.0.30=h7e086dd_0
  - nitro=2.7.dev8=h1537add_0
  - numpy=1.22.4=py310hed7ac4c_0
  - opencv=4.5.5=py310h5588dad_13
  - openh264=2.3.1=h63175ca_2
  - openjpeg=2.5.0=hc9384bd_1
  - openmp=8.0.1=0
  - openssl=1.1.1w=hcfcfb64_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310hb4db72f_1
  - pcl=1.12.1=ha16db99_2
  - pcre=8.45=h0e60522_0
  - pcre2=10.43=h17e33f8_0
  - pdal=2.4.3=hf82e275_2
  - pillow=9.2.0=py310hd4fb230_3
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - ply=3.11=pyhd8ed1ab_3
  - poppler=22.04.0=hea5ffa9_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=14.5=h392df6f_3
  - proj=9.0.1=h1cfcee9_1
  - psutil=5.9.8=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pugixml=1.11.4=h63175ca_1
  - py-opencv=4.5.5=py310hbbfc1a7_13
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.7=py310hbabf5d4_0
  - pyqt5-sip=12.11.0=py310h8a704f9_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.8=h0269646_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt=5.15.4=h2d74725_0
  - qt-main=5.15.4=h467ea89_2
  - qt-webengine=5.15.4=h7325c83_3
  - quaternion=2024.0.13=py310h8f3aa81_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scipy=1.8.1=py310h578b7cb_3
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.6.2=py310h8a704f9_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinx_rtd_theme=3.0.2=pyha770c72_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlite=3.51.1=hdb435a2_0
  - svt-av1=1.4.1=h63175ca_0
  - tbb=2022.1.0=ha82c486_0
  - tbb-devel=2022.1.0=h47441b3_0
  - tiledb=2.11.3=h5689973_1
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.3=py310h29418f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.8=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - vtk=9.1.0=qt_py310hbebbbde_214
  - wheel=0.45.1=pyhd8ed1ab_1
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zlib=1.2.13=h2466b09_6
  - zstandard=0.23.0=py310h29418f3_3
  - zstd=1.5.6=h0ea2cb4_0
